### ISSUE TITLE
README.md - Revisar

### ISSUE THREAD

**Issue by leonardo-minora** [PI-InfoWeb-CNAT/Malfatti#1]
Colocar as informações da equipe no README.

- [x] @jainneagatha Jainne Agatha
- [x] @laiz234 Laiz Fernanda
- [x] @leonardo-minora Leonardo Ataide
- [x] @leticiamaiaa Letícia Maia
- [x] @Maria-Ricarte Maria Clara
- [x] @winniealmeida Winnie Almeida

**Comment by Maria-Ricarte** [comment]
Todos os integrantes adicionados ao README.
