### ISSUE TITLE
CDU Gerenciar Cliente - Revisar

### ISSUE THREAD

**Issue by leonardo-minora** [PI-InfoWeb-CNAT/Malfatti#5]
Revisar documento [CDU Gerenciar cliente](https://github.com/PI-InfoWeb-CNAT/Malfatti/blob/main/docs/CDUs/CDU-Gerenciar_Cliente.md) com as seguintes metas:

1. Apagar informações que não pertencem a especificação do caso de uso
2. Revisar fluxo princial, colocando nele apenas a consulta (C do CRUD)
3. Revisar fluxo alternativo, colocando nele criar, atualizar e apagar (RUD do CRUD)
4. Colocar o protótipo de tela no CDU

**Comment by Maria-Ricarte** [comment]
Documento de gerenciamento de usuário alterado. Protótipo adicionado.
